# Fase de Build
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
WORKDIR "/src/StellarGear.API"
RUN dotnet restore "StellarGear.API.csproj"
RUN dotnet build "StellarGear.API.csproj" -c Release -o /app/build
RUN dotnet publish "StellarGear.API.csproj" -c Release -o /app/publish

# Fase de Runtime (Segurança: Utilizador não-root)
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
RUN useradd -m fiapuser
USER fiapuser

COPY --from=build /app/publish .

EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT ["dotnet", "StellarGear.API.dll"]